[versions]
agp = "8.6.1"
kotlin = "2.1.21"
nexus-publish = "2.0.0-rc-1"
android-minSdk = "24"
android-compileSdk = "35"
coroutines = "1.10.2"
kotlinxDatetime = "0.6.2"
frog = "5.2.0"
drpub = "0.3.33"
log4j = "2.23.1"
kotlinxSerialization = "1.8.1"
dokka = "2.0.0"
atomicfu = "0.28.0" #wersja 0.29 wymaga nowszego kotlina 2.2


[libraries]
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
nexus-publish = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j"}
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jfrogArtifactory = { id = "com.jfrog.artifactory", version.ref = "frog" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
drpublish = { id = "pl.dronline.publish", version.ref = "drpub" }
